# .github/workflows/frontend-tests.yml
name: Frontend Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Run ESLint
      run: |
        cd frontend
        npm run lint || echo "No lint command configured, skipping"
        
    - name: Run tests
      run: |
        cd frontend
        npm test -- --passWithNoTests
        
    - name: Build
      run: |
        cd frontend
        npm run build