# .github/workflows/security.yml
name: Security Scanning

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  push:
    branches: [ main ]
    paths:
      - 'backend/requirements.txt'
      - 'frontend/package.json'

jobs:
  backend-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety
        
    - name: Scan backend dependencies
      run: |
        safety check -r backend/requirements.txt

  frontend-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        
    - name: Run npm audit
      run: |
        cd frontend
        npm audit || true  # Don't fail the build, just generate a report